services:
  db:
    image: postgres:17
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: root_password
    ports:
      - "5050:80"
    networks:
      - laravel_network

  laravelapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always 
    volumes:
      - ./project:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - db
    networks:
      - laravel_network


volumes:
  pgdata: {}
  
networks:
  laravel_network: